export const FETCH_BEERS_BY_NAME = "FETCH_BEERS_BY_NAME"
export const FETCH_BEERS_BY_NAME_SUCCESS = "FETCH_BEERS_BY_NAME_SUCCESS"
export const FETCH_BEERS_BY_NAME_FAILURE = "FETCH_BEERS_BY_NAME_FAILURE"
export const CANCEL_SEARCH = "CANCEL_SEARCH"